version: "3.1"

services:
  web:
    image: nginx
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www:z
      - ${WEB_LOG_DIR-./docker/logs/nginx}:/var/log/nginx:z
      - ${NGINX_CONFIG-./docker/config/nginx}:/etc/nginx/conf.d:z
    ports:
      - "${HOST_MACHINE_UNSECURE_HOST_PORT-8080}:80"
    links:
      - php
    environment:
      - NGINX_HOST=localhost
      - NGINX_PORT=80
  php:
    build:
      context: docker/php7.4
    links:
      - mysql
    working_dir: /var/www
    volumes:
      - ${DOCUMENT_ROOT-./www}:/var/www:z
      - ${PHP_INI-./config/php/php.ini}:/usr/local/etc/php/php.ini:z
      - ${PHP_XDEBUG_INI-./config/php/xdebug.ini}:/usr/local/etc/php/conf.d/xdebug.ini:z
  mysql:
    image: mysql
    ports:
      - "${HOST_MACHINE_MYSQL_PORT}:3306"
    volumes:
      - ${MYSQL_DATA_DIR-./docker/data/mysql}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./docker/logs/mysql}:/var/log/mysql
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD-secret}
      MYSQL_DATABASE: ${MYSQL_DATABASE-test_db}
      MYSQL_USER: ${MYSQL_USER-admin}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD-secret}
